### ISSUE TITLE
请问这个项目能实现以下的目标吗？

### ISSUE THREAD

**Issue by Stephenfang51** [zacario-li/OneClassSVM#1]
您好

谢谢您的分享， 近期忙碌需要在找时间测试

假设我现在有两个类 A和B 但由于B的样本 实际种类太庞大， 不好搜集， 打算以A类做正样本

那么和A类差距较大的都会是属于B类， 这样的方式训练模型

不晓得这样的需求 您试过吗？

谢谢 ！

**Comment by zacario-li** [comment]
可以，这就是这个代码的目的

**Comment by Stephenfang51** [comment]
尝试了一下您的代码

出现如下报错
看起来是在读取pretrained models时候出了维度的问题

抱歉tensorflow跟keras用的少， 想请问这如何解决， 谢谢！

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-f45697004e46> in <module>
    102 
    103 if __name__ == '__main__':
--> 104     trainSVM()
    105     loadSVMAndPredict()
    106     pass

<ipython-input-3-f45697004e46> in trainSVM()
     66 
     67 def trainSVM():
---> 68     f = OCSVM()
     69     X_train = f.prepareData('data/train')
     70     # do StandardScaler

<ipython-input-3-f45697004e46> in __init__(self)
      3         self.model = ResNet50(input_shape=(224, 224,3),weights=None,include_top=False)
      4         # the weights below downloaded from ('https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
----> 5         self.model.load_weights('resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
      6         self.ss = StandardScaler()
      7         self.ocsvmclf = svm.OneClassSVM(gamma=0.001,

/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
    490                 os.remove(tmp_filepath)
    491             return res
--> 492         return load_function(*args, **kwargs)
    493 
    494     return load_wrapper

/usr/local/lib/python3.6/dist-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
   1228             else:
   1229                 saving.load_weights_from_hdf5_group(
-> 1230                     f, self.layers, reshape=reshape)
   1231             if hasattr(f, 'close'):
   1232                 f.close()

/usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
   1235                              ' elements.')
   1236         weight_value_tuples += zip(symbolic_weights, weight_values)
-> 1237     K.batch_set_value(weight_value_tuples)
   1238 
   1239 

/usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
   2958             `value` should be a Numpy array.
   2959     """
-> 2960     tf_keras_backend.batch_set_value(tuples)
   2961 
   2962 

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in batch_set_value(tuples)
   3316     with ops.init_scope():
   3317       for x, value in tuples:
-> 3318         x.assign(np.asarray(value, dtype=dtype(x)))
   3319   else:
   3320     with get_graph().as_default():

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
    812     with _handle_graph(self.handle):
    813       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
--> 814       self._shape.assert_is_compatible_with(value_tensor.shape)
    815       assign_op = gen_resource_variable_ops.assign_variable_op(
    816           self.handle, value_tensor, name=name)

/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
   1113     """
   1114     if not self.is_compatible_with(other):
-> 1115       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
   1116 
   1117   def most_specific_compatible_shape(self, other):

ValueError: Shapes (1, 1, 128, 512) and (512, 256, 1, 1) are incompatible
```

**Comment by zacario-li** [comment]
> 尝试了一下您的代码
> 
> 出现如下报错
> 看起来是在读取pretrained models时候出了维度的问题
> 
> 抱歉tensorflow跟keras用的少， 想请问这如何解决， 谢谢！
> 
> ```
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-3-f45697004e46> in <module>
>     102 
>     103 if __name__ == '__main__':
> --> 104     trainSVM()
>     105     loadSVMAndPredict()
>     106     pass
> 
> <ipython-input-3-f45697004e46> in trainSVM()
>      66 
>      67 def trainSVM():
> ---> 68     f = OCSVM()
>      69     X_train = f.prepareData('data/train')
>      70     # do StandardScaler
> 
> <ipython-input-3-f45697004e46> in __init__(self)
>       3         self.model = ResNet50(input_shape=(224, 224,3),weights=None,include_top=False)
>       4         # the weights below downloaded from ('https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
> ----> 5         self.model.load_weights('resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
>       6         self.ss = StandardScaler()
>       7         self.ocsvmclf = svm.OneClassSVM(gamma=0.001,
> 
> /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
>     490                 os.remove(tmp_filepath)
>     491             return res
> --> 492         return load_function(*args, **kwargs)
>     493 
>     494     return load_wrapper
> 
> /usr/local/lib/python3.6/dist-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
>    1228             else:
>    1229                 saving.load_weights_from_hdf5_group(
> -> 1230                     f, self.layers, reshape=reshape)
>    1231             if hasattr(f, 'close'):
>    1232                 f.close()
> 
> /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
>    1235                              ' elements.')
>    1236         weight_value_tuples += zip(symbolic_weights, weight_values)
> -> 1237     K.batch_set_value(weight_value_tuples)
>    1238 
>    1239 
> 
> /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
>    2958             `value` should be a Numpy array.
>    2959     """
> -> 2960     tf_keras_backend.batch_set_value(tuples)
>    2961 
>    2962 
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in batch_set_value(tuples)
>    3316     with ops.init_scope():
>    3317       for x, value in tuples:
> -> 3318         x.assign(np.asarray(value, dtype=dtype(x)))
>    3319   else:
>    3320     with get_graph().as_default():
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
>     812     with _handle_graph(self.handle):
>     813       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
> --> 814       self._shape.assert_is_compatible_with(value_tensor.shape)
>     815       assign_op = gen_resource_variable_ops.assign_variable_op(
>     816           self.handle, value_tensor, name=name)
> 
> /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
>    1113     """
>    1114     if not self.is_compatible_with(other):
> -> 1115       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
>    1116 
>    1117   def most_specific_compatible_shape(self, other):
> 
> ValueError: Shapes (1, 1, 128, 512) and (512, 256, 1, 1) are incompatible
> ```

This h5 model is tensorflow based, you should choose your correct model file depend on your backend.

**Comment by Stephenfang51** [comment]
尝试了没有用预训练模型， 不过test的结果都显示-1表示都属于负样本 也就是另一类吗？

**Comment by zacario-li** [comment]
> 尝试了没有用预训练模型， 不过test的结果都显示-1表示都属于负样本 也就是另一类吗？

不用预训练模型肯定是不行的。
1:属于训练集图片分布那一类
-1:不属于训练集分布一类

**Comment by Wangjyddddddd** [comment]
> > 尝试了一下您的代码
> > 出现如下报错
> > 看起来是在读取pretrained models时候出了维度的问题
> > 抱歉tensorflow跟keras用的少， 想请问这如何解决， 谢谢！
> > ```
> > ---------------------------------------------------------------------------
> > ValueError                                Traceback (most recent call last)
> > <ipython-input-3-f45697004e46> in <module>
> >     102 
> >     103 if __name__ == '__main__':
> > --> 104     trainSVM()
> >     105     loadSVMAndPredict()
> >     106     pass
> > 
> > <ipython-input-3-f45697004e46> in trainSVM()
> >      66 
> >      67 def trainSVM():
> > ---> 68     f = OCSVM()
> >      69     X_train = f.prepareData('data/train')
> >      70     # do StandardScaler
> > 
> > <ipython-input-3-f45697004e46> in __init__(self)
> >       3         self.model = ResNet50(input_shape=(224, 224,3),weights=None,include_top=False)
> >       4         # the weights below downloaded from ('https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
> > ----> 5         self.model.load_weights('resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
> >       6         self.ss = StandardScaler()
> >       7         self.ocsvmclf = svm.OneClassSVM(gamma=0.001,
> > 
> > /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
> >     490                 os.remove(tmp_filepath)
> >     491             return res
> > --> 492         return load_function(*args, **kwargs)
> >     493 
> >     494     return load_wrapper
> > 
> > /usr/local/lib/python3.6/dist-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
> >    1228             else:
> >    1229                 saving.load_weights_from_hdf5_group(
> > -> 1230                     f, self.layers, reshape=reshape)
> >    1231             if hasattr(f, 'close'):
> >    1232                 f.close()
> > 
> > /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
> >    1235                              ' elements.')
> >    1236         weight_value_tuples += zip(symbolic_weights, weight_values)
> > -> 1237     K.batch_set_value(weight_value_tuples)
> >    1238 
> >    1239 
> > 
> > /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
> >    2958             `value` should be a Numpy array.
> >    2959     """
> > -> 2960     tf_keras_backend.batch_set_value(tuples)
> >    2961 
> >    2962 
> > 
> > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in batch_set_value(tuples)
> >    3316     with ops.init_scope():
> >    3317       for x, value in tuples:
> > -> 3318         x.assign(np.asarray(value, dtype=dtype(x)))
> >    3319   else:
> >    3320     with get_graph().as_default():
> > 
> > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
> >     812     with _handle_graph(self.handle):
> >     813       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
> > --> 814       self._shape.assert_is_compatible_with(value_tensor.shape)
> >     815       assign_op = gen_resource_variable_ops.assign_variable_op(
> >     816           self.handle, value_tensor, name=name)
> > 
> > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
> >    1113     """
> >    1114     if not self.is_compatible_with(other):
> > -> 1115       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
> >    1116 
> >    1117   def most_specific_compatible_shape(self, other):
> > 
> > ValueError: Shapes (1, 1, 128, 512) and (512, 256, 1, 1) are incompatible
> > ```
> 
> This h5 model is tensorflow based, you should choose your correct model file depend on your backend.

我也遇到了这个问题，我是google colab跑的，请问怎么选取合适的模型可以详细说说吗？

**Comment by zacario-li** [comment]
> > > 尝试了一下您的代码
> > > 出现如下报错
> > > 看起来是在读取pretrained models时候出了维度的问题
> > > 抱歉tensorflow跟keras用的少， 想请问这如何解决， 谢谢！
> > > ```
> > > ---------------------------------------------------------------------------
> > > ValueError                                Traceback (most recent call last)
> > > <ipython-input-3-f45697004e46> in <module>
> > >     102 
> > >     103 if __name__ == '__main__':
> > > --> 104     trainSVM()
> > >     105     loadSVMAndPredict()
> > >     106     pass
> > > 
> > > <ipython-input-3-f45697004e46> in trainSVM()
> > >      66 
> > >      67 def trainSVM():
> > > ---> 68     f = OCSVM()
> > >      69     X_train = f.prepareData('data/train')
> > >      70     # do StandardScaler
> > > 
> > > <ipython-input-3-f45697004e46> in __init__(self)
> > >       3         self.model = ResNet50(input_shape=(224, 224,3),weights=None,include_top=False)
> > >       4         # the weights below downloaded from ('https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
> > > ----> 5         self.model.load_weights('resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5')
> > >       6         self.ss = StandardScaler()
> > >       7         self.ocsvmclf = svm.OneClassSVM(gamma=0.001,
> > > 
> > > /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_wrapper(*args, **kwargs)
> > >     490                 os.remove(tmp_filepath)
> > >     491             return res
> > > --> 492         return load_function(*args, **kwargs)
> > >     493 
> > >     494     return load_wrapper
> > > 
> > > /usr/local/lib/python3.6/dist-packages/keras/engine/network.py in load_weights(self, filepath, by_name, skip_mismatch, reshape)
> > >    1228             else:
> > >    1229                 saving.load_weights_from_hdf5_group(
> > > -> 1230                     f, self.layers, reshape=reshape)
> > >    1231             if hasattr(f, 'close'):
> > >    1232                 f.close()
> > > 
> > > /usr/local/lib/python3.6/dist-packages/keras/engine/saving.py in load_weights_from_hdf5_group(f, layers, reshape)
> > >    1235                              ' elements.')
> > >    1236         weight_value_tuples += zip(symbolic_weights, weight_values)
> > > -> 1237     K.batch_set_value(weight_value_tuples)
> > >    1238 
> > >    1239 
> > > 
> > > /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py in batch_set_value(tuples)
> > >    2958             `value` should be a Numpy array.
> > >    2959     """
> > > -> 2960     tf_keras_backend.batch_set_value(tuples)
> > >    2961 
> > >    2962 
> > > 
> > > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/keras/backend.py in batch_set_value(tuples)
> > >    3316     with ops.init_scope():
> > >    3317       for x, value in tuples:
> > > -> 3318         x.assign(np.asarray(value, dtype=dtype(x)))
> > >    3319   else:
> > >    3320     with get_graph().as_default():
> > > 
> > > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/resource_variable_ops.py in assign(self, value, use_locking, name, read_value)
> > >     812     with _handle_graph(self.handle):
> > >     813       value_tensor = ops.convert_to_tensor(value, dtype=self.dtype)
> > > --> 814       self._shape.assert_is_compatible_with(value_tensor.shape)
> > >     815       assign_op = gen_resource_variable_ops.assign_variable_op(
> > >     816           self.handle, value_tensor, name=name)
> > > 
> > > /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/tensor_shape.py in assert_is_compatible_with(self, other)
> > >    1113     """
> > >    1114     if not self.is_compatible_with(other):
> > > -> 1115       raise ValueError("Shapes %s and %s are incompatible" % (self, other))
> > >    1116 
> > >    1117   def most_specific_compatible_shape(self, other):
> > > 
> > > ValueError: Shapes (1, 1, 128, 512) and (512, 256, 1, 1) are incompatible
> > > ```
> > 
> > 
> > This h5 model is tensorflow based, you should choose your correct model file depend on your backend.
> 
> 我也遇到了这个问题，我是google colab跑的，请问怎么选取合适的模型可以详细说说吗？

我抽空写成pytorch版本吧，tensorflow很多年不用了，忘记了。

**Comment by Wangjyddddddd** [comment]
如果可以的话，非常感激。

**Comment by zacario-li** [comment]
> 如果可以的话，非常感激。

我突然有个想法，我想让ChatGPT帮我把这段代码改成pytorch的，不知道效果怎么样

**Comment by wangwenying1** [comment]
> > 如果可以的话，非常感激。
> 
> 我突然有个想法，我想让ChatGPT帮我把这段代码改成pytorch的，不知道效果怎么样

请问这个代码您改成pytorch了吗

**Comment by bobo-liang** [comment]
您好，请问有pytorch版本了吗？

**Comment by zacario-li** [comment]
> 您好，请问有pytorch版本了吗？

已经好了，请使用ocsvm_torch.py @bobo-liang @Wangjyddddddd @wangwenying1

**Comment by wangwenying1** [comment]
好的，非常感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月31日(周五) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zacario-li/OneClassSVM] 请问这个项目能实现以下的目标吗？ (#1)




  
您好，请问有pytorch版本了吗？
  
已经好了，请使用ocsvm_torch.py
